DROP TABLE IF EXISTS [groups];
CREATE TABLE IF NOT EXISTS [groups] (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name STRING UNIQUE
);

DROP TABLE IF EXISTS teachers;
CREATE TABLE IF NOT EXISTS teachers (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname STRING UNIQUE
);
DROP TABLE IF EXISTS students;
CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname STRING UNIQUE,
	group_id REFERENCES [groups] (id)
);
DROP TABLE IF EXISTS disciplines;
CREATE TABLE IF NOT EXISTS disciplines (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name STRING,
	teacher_id REFERENCES teachers (id)
);
DROP TABLE IF EXISTS grades;
CREATE TABLE IF NOT EXISTS grades (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	disciplines_id REFERENCES disciplines (id),
	students_id REFERENCES students (id),
	grade INTEGER,
	date_of DATE
);